config/routes.rb
Planetafutebol::Application.routes.draw do


  resources :clubs, :path => 'clubes', :only => [:index, :show] do
    resources :articles, :path => 'noticias'
  end

  match 'clube/:slug' => 'clubs#show', :as => 'clube'
  match 'clube/:slug/noticias/:title' => 'articles#show', :as => 'noticia'
  
  root :to => 'clubs#index'

  match 'sobre' => 'pages#sobre'

  match 'contato' => 'contact#new', :as => 'contact', :via => :get
  match 'contato' => 'contact#create', :as => 'contact', :via => :post
end

app/models/article.rb
class Article
  include Mongoid::Document
  field :title, :type => String
  field :summary, :type => String
  field :content, :type => String
  field :author, :type => String
  field :url, :type => String
  field :slug, :type => String
  field :published_at, :type => Time

  validates_uniqueness_of :title, message: "Title thould be unique"
  validates_uniqueness_of :content
  validates_presence_of :content

  belongs_to :club
  belongs_to :source
  
  before_save :slugify!
  
  def slugify!
    self.slug = title.downcase.strip.gsub(' ', '-').mb_chars.normalize(:kd).gsub(/[^\-x00-\x7F]/n, '').to_s
  end

  index(
    [
      [:title, Mongo::ASCENDING]
    ],
    unique: true
  )

end

app/models/club.rb
class Club
  include Mongoid::Document
  field :name, :type => String
  field :website, :type => String
  field :twitter, :type => String
  field :slug, :type => String

  validates_presence_of :name, :website
  validates_uniqueness_of :name, :website

  has_many :sources
  has_many :articles

  before_create :generate_slug

  index([
    [:name, Mongo::ASCENDING]
  ],
    unique: true
  )

  def generate_slug
    self.slug = small_name 
  end

  private
  def small_name
    name.downcase.mb_chars.normalize(:kd).gsub(/[^\-x00-\x7F]/n, '').to_s
  end

end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/source.rb
class Source
  include Mongoid::Document
  field :name, type: String
  field :website, type: String
  field :url, type: String
  field :parsed_at, :type => Time, default: (Time.now - 5.days) 
  belongs_to :club
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.where(:slug => params[:id]).first
  end

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

  def index
    @clubs = Club.all
  end

  def show
    @club = Club.where(:slug => params[:slug]).first
    @articles = @club.articles.desc(:published_at).page(params[:page])
    respond_to do |format|
      format.html
      format.json
      format.rss { render :layout => false }
    end
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  layout 'application'

  def sobre
  end

  def contato
  end

end

app/helpers/application_helper.rb
# encoding: UTF-8
module ApplicationHelper
  def site_title
    title = ""
    resource = main_resource
    return title << "Notícias atualizadas sobre futebol | Vole.io" unless resource
    if resource.is_a?(Club)
      title << "Notícias sobre o clube #{resource.name}" 
    elsif resource.is_a?(Article)
      title << "#{resource.title}"
    end
    title << ' | Vole.io'
    title
  end

  def breadcrumbs_for(resource)
    link = content_tag(:a, 'Home', href: '/')
    link << content_tag('span', '/', :class => 'divider')
    breadcrumb = content_tag(:li, link )
    if resource.is_a?(Club)
      breadcrumb << content_tag('li', resource.name, class: 'active')
    else
      breadcrumb << content_tag('li', resource.club.name)
    end
    breadcrumb
  end

  def image_for(club)
    return "" unless club.name
    name = club.name.downcase.strip.gsub(' ', '-').mb_chars.normalize(:kd).gsub(/[^\-x00-\x7F]/n, '').to_s
    "#{name}.png"
  end

  private
  def main_resource
    @article || @club
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/articles/show.html.slim
.row
  article(class="news span8 offset2" itemtype="http://schema.org/Article" itemscope)
    header
      .source-url = @article.source.name
      .article-title
        h1 itemprop="headline" = @article.title
      .article-info
        ul
          li.first
            span.author itemprop="author" = link_to "Link original", @article.url
          li
            span.date itemprop="dateCreated" = I18n.l @article.published_at, :format => :short
      .sharing.hidden-phone
        = render partial: 'shared/tweet_this'

    section.content itemprop="articleBody"
      = raw @article.content

    footer
      p = link_to "Voltar", clube_path(@article.club.slug)

app/views/clubs/_club_twitter.html.slim
erb:
  <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
  <script>
  new TWTR.Widget({
    version: 2,
    type: 'profile',
    rpp: 4,
    interval: 30000,
    width: 220,
    height: 300,
    theme: {
      shell: {
        background: '#333333',
        color: '#ffffff'
      },
      tweets: {
        background: '#ffffff',
        color: '#333333',
        links: '#378194'
      }
    },
    features: {
      scrollbar: false,
      loop: false,
      live: false,
      behavior: 'all'
    }
  }).render().setUser('<%= @club.twitter %>').start();
  </script>

app/views/clubs/index.html.slim
.row
  .span12
    = render "shared/hero"
    .page-header.hidden-phone
      h1 Escolha seu clube
    .row
      .span6
        ul.club-list
          - @clubs.each do |club|
            li.span1.club
              = link_to clube_path(:slug => club.slug) do
                .thumbnail
                  = image_tag image_for(club), alt: club.name
        .clear
        .sobre
          p Saiba mais #{link_to 'sobre o Vole.io.', '/sobre'}
      .span6
        .contato.hidden-phone
          h2 Deseja ver seu time no Vole.io?
          p Então entre #{ link_to 'em contato conosco.', contact_path}

          = render partial: 'shared/twitter.html.slim'
          = render partial: 'shared/facebook_like.html.slim'

app/views/clubs/show.html.slim
= auto_discovery_link_tag(:rss, clube_url(@club.name, :format => :rss))
.row
  div(class="span12 #{@club.slug} show" itemtype="http://schema.org/SportsTeam" itemscope)
    = render "shared/hero"
    ul.breadcrumb.hidden-phone
      = breadcrumbs_for @club
    .page-header
      h1.title itemprop="name" = @club.name
      span.rss.hidden-phone = image_tag 'rss.png'
    .row
      .article-list.span8
        - @articles.each do |article|
          article.summary
                  
            h3 = link_to article.title, club_article_path(@club.slug, article.slug)

            p.article-summary.hidden-phone
              span.source
                = link_to article.source.name, article.source.website
                |  - 
              = raw article.summary 
              br
              span.date=" há #{distance_of_time_in_words(article.published_at, Time.now)}"
        .pagination
          ul
            = paginate @articles
  
      .span4
        .thumbnail.info-box.hidden-phone
          h4= @club.name
          = image_tag "#{@club.slug}-medium.gif", alt: @club.name
          .caption
            h4= @club.name
            p.website= link_to "Site oficial", @club.website 
        = render partial: "club_twitter"

app/views/contact/_form.html.slim
= form_for @message, :url => contact_path, :class => 'form-horizontal' do |form|
  fieldset
    legend Deixe seu recado
    .control-group
      = form.label :nome, class: "control-label"
      .controls
        = form.text_field :name, class: "input-xlarge"

      = form.label :email, class: "control-label"
      .controls
        = form.text_field :email, class: "input-xlarge"
        p class="help-block"
          | Informe seu email para que possamos retornar sua mensagem

      = form.label :mensagem, class: "control-label"
      .controls
        = form.text_area :body, class: "input-xlarge", rows: 3
  fieldset class="actions"
    = form.submit "Send"

app/views/contact/new.html.slim
= render partial: "shared/hero"
.span12
  .page-header
    h1 Contato
  .row
    .span6
      h2 Reclamações e Sugestões
      p O Vole.io é um projeto criado por um amante de futebol. Se você também se considera um fanático pelo esporte bretão, sua contribuição é muito importante para mim.
      p Críticas e sugestões serão muito bem-vindas.

      h2 Indique seu Time
      p A meta deste site é cobrir os principais clubes de futebol nacionais. Porém, estes serão adicionados em etapas baseadas em procura e pedidos de visitantes. Use o formulário ao lado para sugerir seu clube e aumentar as chances de ele fazer parte do Vole.io.
    .span6
      = render partial: "form"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta http-equiv="Content-Type" content="text/html; charset=charset=utf-8"
    meta name="description" content="Notícias atualizadas sobre os principais clubes do futebol brasileiro."
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"
    title #{site_title} 

    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = render partial: "shared/facebook_meta_tags"
    = render partial: "shared/analytics"
  body
    = render partial: "shared/facebook_header"
    = render partial: 'shared/top_menu'
    .container
      = yield
      = render partial: 'shared/footer'

app/views/pages/contato.html.slim
= render partial: "shared/hero"
.span12
  .page-header
    h1 Contato
  .row
    .span6
      h2 Reclamações e Sugestões
      p O Vole.io é um projeto criado por um amante de futebol. Se você também se considera um fanático pelo esporte bretão, sua contribuição é muito importante para mim.
      p Críticas e sugestões serão muito bem-vindas.

      h2 Indique seu Time
      p A meta deste site é cobrir os principais clubes de futebol nacionais. Porém, estes serão adicionados em etapas baseadas em procura e pedidos de visitantes. Use o formulário ao lado para sugerir seu clube e aumentar as chances de ele fazer parte do Vole.io.
    .span6
      = render partial: "contact/form"

app/views/pages/show.html.slim
= render :partial => @page_name

app/views/pages/sobre.html.slim
= render partial: "shared/hero"

div(class="about span12" itemscope itemtype="http://schema.org/AboutPage")
  .page-header
    h1 O que é o Vole.io?
  .row
    .span6 itemprop="text"
      p Vole.io é um agregador de notícias de futebol, criado por um fanático como hobby. Este é um projeto pessoal, sem qualquer apoio de empresas ou grupos jornalísticos.

      h2 Qual a origem das notícias?
      p As notícias são coletadas dos principais portais esportivos e blogs especializados. Após as fontes serem manualmente escolhidas, o conteúdo é atualizado automaticamente durante o dia.
      p 
        | Caso você tenha reclamações, sugestões de sites ou deseja outras informações, 
        = link_to 'entre em contato.', '/contato'

app/views/shared/_analytics.html.slim
javascript:
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30975514-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/shared/_facebook_header.html.slim
#fb-root
  javascript:
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=9160203996";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

app/views/shared/_facebook_like.html.slim
.share
  .fb-like data-href="http://vole.io" data-send="false" data-width="300" data-show-faces="true"

app/views/shared/_facebook_meta_tags.html.slim
meta property="og:title" content="Notícias atualizadas sobre futebol | Vole.io "
meta property="og:type" content="sport"
meta property="og:url" content="http://vole.io"
meta property="og:image" content="http://vole.io/assets/logo.png"
meta property="og:site_name" content="Vole.io"
meta property="fb:admins" content="553468866"

app/views/shared/_footer.html.slim
.row-fluid
  footer.footer
    p.pull-right 
      a href="#" Topo
    p Vole.io - 2012 

app/views/shared/_hero.html.slim
.row
  .span12
    .hero-unit.hidden-phone
      .site-logo
        h1 Vole.io
        p.site-title Notícias futebolísticas de primeira sobre o seu time preferido.
  .span4

app/views/shared/_top_menu.html.slim
#top-menu.hidden-phone
  .offset1
    ul.nav
      li.active
        = link_to 'Vole.io', '/', :class => 'brand'
      li
        a href="/clube/internacional"
          img alt="Internacional" src="/assets/internacional.png"
      li
        a href="/clube/gremio"
          img alt="Grêmio" src="/assets/gremio.png"
      li
        a href="/clube/flamengo"
          img alt="Flamengo" src="/assets/flamengo.png"
      li
        a href="/clube/corinthians"
          img alt="Corinthians" src="/assets/corinthians.png"
      li
        a href="/clube/saopaulo"
          img alt="São Paulo" src="/assets/sao-paulo.png"
      li
        a href="/clube/vasco"
          img alt="Vasco" src="/assets/vasco.png"
      li
        a href="/clube/palmeiras"
          img alt="Palmeiras" src="/assets/palmeiras.png"
      li
        a href="/clube/fluminense"
          img alt="Fluminense" src="/assets/fluminense.png"
      li
        a href="/clube/botafogo"
          img alt="Botafogo" src="/assets/botafogo.png"
      li
        a href="/clube/santos"
          img alt="Santos" src="/assets/santos.png"
      li 
        a href="/clube/cruzeiro"
          img alt="Cruzeiro" src="/assets/cruzeiro.png"
      li
        a href="/clube/atletico-mg"
          img alt="Atlético-MG" src="/assets/atletico-mg.png"
.site-title.visible-phone
  = link_to '/' do
    h1 Vole.io

app/views/shared/_tweet_this.html.slim
erb:
  <a href="https://twitter.com/share" class="twitter-share-button" data-via="vole_io" data-lang="pt">Tweetar</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/shared/_twitter.html.slim
a href="https://twitter.com/share" class="twitter-share-button" data-via="vole_io" data-lang="pt" data-size="large" data-related="vole_io"
  | Tweetar
javascript:
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");